<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\CommonPackageHandling.targets" />
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>

		<Description>LazyStack Base</Description>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Remove="ILzMessages.cs" />
	</ItemGroup>
	<ItemGroup>
	  <Content Remove="IInternetConnectivitySvc.cs" />
	  <Content Remove="Messages\DocMetaData.cs" />
	  <Content Remove="Messages\LzMessageSetSelector.cs" />
	  <Content Remove="Messages\MessageDoc.cs" />
	  <Content Remove="Messages\MsgItem.cs" />
	</ItemGroup>

</Project>
