<Project Sdk="Microsoft.NET.Sdk.Razor">
	<Import Project="..\CommonPackageHandling.targets" />
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>

		<Description>LazyStack Blazorise Auth component</Description>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
		<RootNamespace>LazyStack.BlazoriseComponents</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
	  <Content Remove="Config\ConfigureLazyStackBlazoriseComponentsAuthMessages.cs" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\LazyStack.Blazorise\LazyStack.BlazoriseComponents.csproj" />
	  <ProjectReference Include="..\LazyStack.Client.ViewModels.Auth\LazyStack.Client.ViewModels.Auth.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <UpToDateCheckInput Remove="_imports.razor" />
	</ItemGroup>

	<ItemGroup>
	  <_ContentIncludedByDefault Remove="_imports.razor" />
	</ItemGroup>

</Project>
