name: Publish NuGet

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x' # Update to your .NET version

    - name: Create NuGet.Config
      run: |
        cat > NuGet.Config << EOF
        <?xml version="1.0" encoding="utf-8"?>
        <configuration>
          <packageSources>
            <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
            <add key="InSciCo" value="https://nuget.pkg.github.com/InSciCo/index.json" />
            <!-- Other package sources -->
          </packageSources>

          <packageSourceMapping>
            <packageSource key="nuget.org">
              <package pattern="*" />
            </packageSource>
            <packageSource key="InSciCo">
              <package pattern="InSciCo.*" />
              <!-- Add other patterns as needed -->
            </packageSource>
          </packageSourceMapping>
        </configuration>
        EOF

    - name: Restore dependencies
      run: |
        dotnet restore

    - name: Build # Build solution
      run: dotnet build --no-restore

    - name: Publish
      run: |
        dotnet nuget push ./Packages/*.nupkg --source https://nuget.pkg.github.com/InSciCo/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
        dotnet nuget push ./Packages/*.snupkg --source https://nuget.pkg.github.com/InSciCo/index.json --api-key ${{ secrets.GITHUB_TOKEN }}